[tool.poetry]
name = "teach-gpt"
version = "0.1.0"
description = ""
authors = ["cm2435 <charlie.masters@xapien.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
torch = "^2.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
